apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 888router

resources:
  - ../../base

images:
  - name: voravitl/888router
    newTag: 0.15.99

labels:
  - pairs:
      environment: production
      deployed-by: kustomize
    includeSelectors: false
