export default {
  id: "kilo-gateway",
  alias: "kgw",
  aliases: [
    "kilo-gateway",
    "kilogateway",
  ],
  uiAlias: "kgw",
  category: "freeTier",
  display: {
    name: "Kilo Gateway",
    icon: "login",
    color: "#8B5CF6",
    textIcon: "KG",
    website: "https://kilo.ai",
    notice: {
      apiKeyUrl: "https://kilo.ai/dashboard?tab=apiKeys",
    },
  },
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://api.kilo.ai/api/gateway/chat/completions",
    validateUrl: "https://api.kilo.ai/api/gateway/models",
  },
  hasFree: true,
  modelsFetcher: { url: "https://api.kilo.ai/api/gateway/models", type: "openrouter-free" },
  passthroughModels: true,
  models: [
    { id: "kilo-auto/free", name: "Kilo Auto Free", contextLength: 256000 },
    { id: "stepfun/step-3.7-flash:free", name: "StepFun Step 3.7 Flash (Free)", contextLength: 262144 },
    { id: "tencent/hy3:free", name: "Tencent Hy3 (Free)", contextLength: 262144 },
    { id: "meituan/longcat-2.0-free", name: "Meituan LongCat 2.0 (Free)", contextLength: 1048756 },
    { id: "poolside/laguna-s-2.1:free", name: "Poolside Laguna S 2.1 (Free)", contextLength: 262144 },
    { id: "inclusionai/ling-3.0-flash-fin:free", name: "InclusionAI Ling 3.0 Flash Fin (Free)", contextLength: 262144 },
    { id: "dots-studio/dots-3-note-preview:free", name: "Dots Studio Dots 3 Note (Free)", contextLength: 262144 },
    { id: "liquid/lfm-2.5-2.6b:free", name: "Liquid LFM 2.5 2.6B (Free)", contextLength: 262144 },
    { id: "nvidia/nemotron-3.5-lightning:free", name: "NVIDIA Nemotron 3.5 Lightning (Free)", contextLength: 262144 },
    { id: "thinkingmachines/inkling-small:free", name: "ThinkingMachines Inkling Small (Free)", contextLength: 262144 },
    { id: "nvidia/nemotron-3-ultra-550b-a55b:free", name: "Nemotron 3 Ultra 550B (Free)", contextLength: 1000000 },
    { id: "nvidia/nemotron-3-super-120b-a12b:free", name: "Nemotron 3 Super 120B (Free)", contextLength: 262144 },
    { id: "kwaipilot/kat-coder-pro-v2.5:free", name: "Kat Coder Pro v2.5 (Free)", contextLength: 256000 },
    { id: "cohere/north-mini-code:free", name: "Cohere North Mini Code (Free)", contextLength: 256000 },
    { id: "openrouter/auto-beta", name: "OpenRouter Auto Router Beta", contextLength: 128000 },
    { id: "openrouter/free", name: "OpenRouter Free Models Router", contextLength: 128000 },
    { id: "kilo-auto/frontier", name: "Kilo Auto Frontier", contextLength: 1000000 },
    { id: "kilo-auto/balanced", name: "Kilo Auto Balanced", contextLength: 1000000 },
  ],
};
