const naraConfig = {
  id: "nara",
  priority: 72,
  hasFree: true,
  alias: "nara",
  aliases: [
    "nararouter",
    "bynara",
    "by-nara",
  ],
  uiAlias: "nara",
  display: {
    name: "NaraRouter (byNara)",
    icon: "router",
    color: "#6366F1",
    textIcon: "NR",
    website: "https://router.bynara.id",
    notice: {
      text: "OpenAI-compatible AI gateway by byNara with daily subscription quotas and PAYG. 7M tokens/day free tier.",
      apiKeyUrl: "https://router.bynara.id",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://router.bynara.id/v1/chat/completions",
    validateUrl: "https://router.bynara.id/v1/models",
  },
  // Seed snapshot from public /pricing page (verified 2026-09-13:
  // 55 models, 10 free surfaces with 7M/day recurring pool on free tier).
  // Full catalogue is fetched via modelsFetcher after adding a key; other ids via passthroughModels.
  models: [
    { id: "agnes-2.5-flash", name: "Agnes 2.5 Flash" },
    { id: "agnes-video-v2.0", name: "Agnes Video V2.0" },
    { id: "claude-fable-5", name: "Claude Fable 5" },
    { id: "claude-fable-5.1", name: "Claude Fable 5.1" },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "claude-opus-4.7-promo", name: "Claude Opus 4.7 Promo" },
    { id: "claude-opus-4.8", name: "Claude Opus 4.8" },
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "claude-opus-5-promo", name: "Claude Opus 5 Promo" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "deepseek-v4-flash-alibaba", name: "DeepSeek V4 Flash Alibaba" },
    { id: "deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision Exp" },
    { id: "deepseek-v4-pro-alibaba", name: "DeepSeek V4 Pro Alibaba" },
    { id: "deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash" },
    { id: "deepseek-v4.1-flash-free", name: "DeepSeek V4.1 Flash Free" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "gemini-3.8-flash-high", name: "Gemini 3.8 Flash High" },
    { id: "glm-5.2", name: "GLM-5.2" },
    { id: "glm-5.3", name: "GLM-5.3" },
    { id: "glm-5.3-flash", name: "GLM-5.3 Flash" },
    { id: "glm-5.3-free", name: "GLM-5.3 Free" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "gpt-6-astra", name: "GPT-6 Astra" },
    { id: "grok-4.6", name: "Grok 4.6" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "laguna-s-2.1", name: "Laguna S 2.1" },
    { id: "ling-3.0-flash-fin-free", name: "Ling 3.0 Flash Fin Free" },
    { id: "mimo-v2.5", name: "MiMo V2.5" },
    { id: "mimo-v2.5-free", name: "MiMo V2.5 Free" },
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "minimax-m3", name: "MiniMax M3" },
    { id: "muse-spark-1.2", name: "Muse Spark 1.2" },
    { id: "muse-spark-1.2-contributor", name: "Muse Spark 1.2 Contributor" },
    { id: "muse-spark-1.3", name: "Muse Spark 1.3" },
    { id: "muse-spark-1.3-contributor", name: "Muse Spark 1.3 Contributor" },
    { id: "muse-spark-1.3-contributor-free", name: "Muse Spark 1.3 Contributor Free" },
    { id: "qwen3.7-flash", name: "Qwen3.7 Flash" },
    { id: "qwen3.8-2.4t", name: "Qwen3.8 2.4T" },
    { id: "qwen3.8-27b", name: "Qwen3.8 27B" },
    { id: "qwen3.8-flash", name: "Qwen3.8 Flash" },
    { id: "qwen3.8-flash-free", name: "Qwen3.8 Flash Free" },
    { id: "qwen3.8-max", name: "Qwen3.8 Max" },
    { id: "qwen3.8-max-alibaba", name: "Qwen3.8 Max Alibaba" },
    { id: "stepfun-3.7-flash", name: "StepFun 3.7 Flash" },
    { id: "tencent-hy3-free", name: "Tencent Hy3 Free" },
    { id: "tencent-hy4-preview", name: "Tencent Hy4 Preview" },
    { id: "agnes-image-2.0-flash", name: "Agnes Image 2.0 Flash" },
    { id: "agnes-image-2.1-flash", name: "Agnes Image 2.1 Flash" },
    { id: "grok-imagine", name: "Grok Imagine" },
    { id: "nano-banana-pro", name: "Nano Banana Pro" },
  ],
  modelsFetcher: { url: "https://router.bynara.id/v1/models", type: "openai" },
  passthroughModels: true,
};

export default naraConfig;
