export default {
  id: "opencode",
  priority: 210,
  hasFree: true,
  alias: "oc",
  aliases: ["opencode", "ocg"],
  uiAlias: "oc",
  display: {
    name: "OpenCode",
    icon: "terminal",
    color: "#E87040",
    textIcon: "OC",
    website: "https://opencode.ai/auth",
    notice: {
      text: "OpenCode Free & OpenCode Go subscription: Access to GLM, Kimi, DeepSeek, MiMo, MiniMax, Qwen models.",
      apiKeyUrl: "https://opencode.ai/auth",
    },
  },
  category: "apikey",
  authModes: ["noauth", "apikey"],
  authHint: "Leave API key empty for OpenCode Free (Zen) mode, or enter your OpenCode Go API key.",
  transport: {
    baseUrl: "https://opencode.ai",
    headers: {
      "x-opencode-client": "desktop",
    },
  },
  modelsFetcher: { url: "https://opencode.ai/zen/v1/models", type: "opencode-free" },
  passthroughModels: true,
  models: [
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "mimo-v2.5", name: "MiMo V2.5" },
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "minimax-m3", name: "MiniMax M3", targetFormat: "claude" },
    { id: "minimax-m2.7", name: "MiniMax M2.7", targetFormat: "claude" },
    { id: "minimax-m2.5", name: "MiniMax M2.5", targetFormat: "claude" },
    { id: "qwen3.7-max", name: "Qwen 3.7 Max", targetFormat: "claude" },
    { id: "qwen3.7-plus", name: "Qwen 3.7 Plus", targetFormat: "claude" },
    { id: "qwen3.6-plus", name: "Qwen 3.6 Plus", targetFormat: "claude" },
  ],
};
