const openaiConfig = {
  id: "openai",
  priority: 30,
  alias: "openai",
  display: {
    name: "OpenAI",
    icon: "auto_awesome",
    color: "#10A37F",
    textIcon: "OA",
    website: "https://platform.openai.com",
    notice: {
      apiKeyUrl: "https://platform.openai.com/api-keys",
    },
  },
  category: "apikey",
  thinkingConfig: {
    options: [
      "auto",
      "none",
      "low",
      "medium",
      "high",
    ],
    defaultMode: "auto",
  },
  transport: {
    baseUrl: "https://api.openai.com/v1/chat/completions",
    forceStream: true,
  },
  // Model list + capabilities verified against models.dev `openai` catalogue on
  // 2026-10-02 (context windows, input modalities, reasoning flags). Keep the
  // newest generation first: the models endpoint merges these into a synced
  // connection so a fresh OpenAI release is selectable before the upstream
  // /v1/models response includes it.
  models: [
    { id: "gpt-6.1-sol", name: "GPT-6.1 Sol", contextWindow: 1050000, vision: true, reasoning: true },
    { id: "gpt-6-astra", name: "GPT-6 Astra", contextWindow: 1050000, vision: true, reasoning: true },
    { id: "gpt-6-sol", name: "GPT-6 Sol", contextWindow: 1050000, vision: true, reasoning: true },
    { id: "gpt-6-luna", name: "GPT-6 Luna", contextWindow: 1050000, vision: true, reasoning: true },
    { id: "gpt-5.6", name: "GPT-5.6", contextWindow: 1050000, vision: true, reasoning: true },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol", contextWindow: 1050000, vision: true, reasoning: true },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", contextWindow: 1050000, vision: true, reasoning: true },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra", contextWindow: 1050000, vision: true, reasoning: true },
    { id: "gpt-5.5", name: "GPT-5.5", contextWindow: 1050000, vision: true, reasoning: true },
    { id: "gpt-5.5-pro", name: "GPT-5.5 Pro", contextWindow: 1050000, vision: true, reasoning: true },
    { id: "gpt-5.4", name: "GPT-5.4", contextWindow: 1050000, vision: true, reasoning: true },
    { id: "gpt-5.4-pro", name: "GPT-5.4 Pro", contextWindow: 1050000, vision: true, reasoning: true },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini", contextWindow: 400000, vision: true, reasoning: true },
    { id: "gpt-5.4-nano", name: "GPT-5.4 Nano", contextWindow: 400000, vision: true, reasoning: true },
    { id: "gpt-5.3-codex", name: "GPT-5.3 Codex", contextWindow: 400000, vision: true, reasoning: true },
    { id: "gpt-5.3-codex-spark", name: "GPT-5.3 Codex Spark", contextWindow: 128000, vision: true, reasoning: true },
    { id: "gpt-5.2", name: "GPT-5.2", contextWindow: 400000, vision: true, reasoning: true },
    { id: "gpt-5.2-pro", name: "GPT-5.2 Pro", contextWindow: 400000, vision: true, reasoning: true },
    { id: "gpt-5.1", name: "GPT-5.1", contextWindow: 400000, vision: true, reasoning: true },
    { id: "gpt-5", name: "GPT-5", contextWindow: 400000, vision: true, reasoning: true },
    { id: "gpt-5-pro", name: "GPT-5 Pro", contextWindow: 400000, vision: true, reasoning: true },
    { id: "gpt-5-mini", name: "GPT-5 Mini", contextWindow: 400000, vision: true, reasoning: true },
    { id: "gpt-5-nano", name: "GPT-5 Nano", contextWindow: 400000, vision: true, reasoning: true },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "gpt-4-turbo", name: "GPT-4 Turbo" },
    { id: "gpt-4.1", name: "GPT-4.1" },
    { id: "gpt-4.1-mini", name: "GPT-4.1 Mini" },
    { id: "gpt-4.1-nano", name: "GPT-4.1 Nano" },
    { id: "o3", name: "O3" },
    { id: "o3-mini", name: "O3 Mini" },
    { id: "o3-pro", name: "O3 Pro" },
    { id: "o4-mini", name: "O4 Mini" },
    { id: "o1", name: "O1" },
    { id: "o1-pro", name: "O1 Pro", contextWindow: 200000, vision: true, reasoning: true },
    { id: "o1-mini", name: "O1 Mini" },
    { id: "text-embedding-3-large", name: "Text Embedding 3 Large", kind: "embedding" },
    { id: "text-embedding-3-small", name: "Text Embedding 3 Small", kind: "embedding" },
    { id: "text-embedding-ada-002", name: "Text Embedding Ada 002", kind: "embedding" },
    { id: "tts-1", name: "TTS-1", kind: "tts" },
    { id: "tts-1-hd", name: "TTS-1 HD", kind: "tts" },
    { id: "gpt-4o-mini-tts", name: "GPT-4o Mini TTS", kind: "tts" },
    { id: "whisper-1", name: "Whisper 1", params: ["language","response_format","temperature","prompt"], kind: "stt" },
    { id: "gpt-4o-transcribe", name: "GPT-4o Transcribe", params: ["language","response_format","temperature","prompt"], kind: "stt" },
    { id: "gpt-4o-mini-transcribe", name: "GPT-4o Mini Transcribe", params: ["language","response_format","temperature","prompt"], kind: "stt" },
    { id: "gpt-image-1", name: "GPT Image 1", params: ["n","size","quality","response_format"], kind: "image" },
    { id: "dall-e-3", name: "DALL-E 3", params: ["size","quality","style","response_format"], kind: "image" },
    { id: "dall-e-2", name: "DALL-E 2", params: ["n","size","response_format"], kind: "image" },
  ],
  serviceKinds: ["llm","embedding","tts","stt","image","imageToText","webSearch"],
  ttsConfig: {
    baseUrl: "https://api.openai.com/v1/audio/speech",
    authType: "apikey",
    authHeader: "bearer",
    format: "openai",
    defaultModel: "gpt-4o-mini-tts",
  },
  sttConfig: {
    baseUrl: "https://api.openai.com/v1/audio/transcriptions",
    authType: "apikey",
    authHeader: "bearer",
    format: "openai",
  },
  embeddingConfig: { baseUrl: "https://api.openai.com/v1/embeddings", authType: "apikey", authHeader: "bearer" },
  imageConfig: { baseUrl: "https://api.openai.com/v1/images/generations" },
  searchViaChat: { defaultModel: "gpt-4o-mini", pricingUrl: "https://openai.com/api/pricing" },
};

export default openaiConfig;
