export default {
  id: "tokenrouter",
  priority: 88,
  display: {
    name: "TokenRouter",
    icon: "tokenrouter",
    color: "#6366F1",
    website: "https://tokenrouter.com",
    notice: {
      signupUrl: "https://tokenrouter.com",
    },
  },
  category: "apikey",
  auth: {
    type: "apikey",
    fields: [
      {
        name: "apiKey",
        label: "API Key",
        type: "password",
        required: true,
        placeholder: "tr-...",
      },
    ],
  },
  transport: {
    baseUrl: "https://api.tokenrouter.com/v1/chat/completions",
    auth: { combined: true, header: "Authorization", scheme: "bearer" },
  },
  models: [
    { id: "MiniMax-Hailuo-2.3", name: "Minimax Hailuo 2.3", kind: "video" },
    { id: "MiniMax-M3", name: "Minimax M3" },
    { id: "anthropic/claude-fable-5", name: "Claude Fable 5" },
    { id: "anthropic/claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "anthropic/claude-opus-4.5", name: "Claude Opus 4.5" },
    { id: "anthropic/claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "anthropic/claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "anthropic/claude-opus-4.7-fast", name: "Claude Opus 4.7 Fast" },
    { id: "anthropic/claude-opus-4.8", name: "Claude Opus 4.8" },
    { id: "anthropic/claude-opus-4.8-fast", name: "Claude Opus 4.8 Fast" },
    { id: "anthropic/claude-opus-5", name: "Claude Opus 5" },
    { id: "anthropic/claude-opus-5-fast", name: "Claude Opus 5 Fast" },
    { id: "anthropic/claude-sonnet-4", name: "Claude Sonnet 4" },
    { id: "anthropic/claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "anthropic/claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "anthropic/claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "deepseek/deepseek-v3.2", name: "Deepseek V3.2" },
    { id: "deepseek/deepseek-v4-flash", name: "Deepseek V4 Flash" },
    { id: "deepseek/deepseek-v4-pro", name: "Deepseek V4 Pro" },
    { id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "google/gemini-3.6-flash", name: "Gemini 3.6 Flash" },
    { id: "moonshotai/kimi-k2.6", name: "Kimi K2.6" },
    { id: "moonshotai/kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "moonshotai/kimi-k3", name: "Kimi K3" },
    { id: "openai/gpt-4o-mini", name: "Gpt 4O Mini" },
    { id: "openai/gpt-5", name: "Gpt 5" },
    { id: "openai/gpt-5.2", name: "Gpt 5.2" },
    { id: "openai/gpt-5.4", name: "Gpt 5.4" },
    { id: "qwen/qwen3-coder-next", name: "Qwen3 Coder Next" },
    { id: "x-ai/grok-4.5", name: "Grok 4.5" },
    { id: "z-ai/glm-5.2", name: "Glm 5.2" },
  ],
  serviceKinds: ["llm", "embedding", "image"],
  embeddingConfig: {
    baseUrl: "https://api.tokenrouter.com/v1/embeddings",
    authType: "apikey",
    authHeader: "bearer",
  },
  imageConfig: {
    baseUrl: "https://api.tokenrouter.com/v1/images/generations",
  },
  modelsFetcher: { url: "https://api.tokenrouter.com/v1/models", type: "openai" },
  passthroughModels: true,
};
