#!/usr/bin/env bash
set -euo pipefail

# Generate and apply K8s secret from local .env without saving secret files to disk.
# Fails closed: any missing, empty, or placeholder value aborts without touching
# the existing Secret. Only ever targets the orbstack context.
#
#   k8s-sync-secret.sh [env-file]           # .env  -> K8s Secret   (default)
#   k8s-sync-secret.sh --pull [out-file]    # K8s Secret -> file   (reverse direction)
#
# --pull materializes the LIVE K8s secret into a dotenv file for a compose
# instance that must authenticate with the same credentials (same JWT_SECRET /
# API_KEY_SECRET / MACHINE_ID_SALT). Defaults to .env.route — gitignored, never
# committed. Non-secret runtime config is taken from configmap/888router-config
# in the same pass so the two instances stay in sync.
# Arg parsing: the first positional arg is either the --pull mode switch or the
# env file for push mode. Keep the two mutually exclusive — a stray positional in
# --pull mode must never fall through to push and overwrite the production Secret.
MODE="push"
ENV_FILE=".env"
case "${1:-}" in
  --pull)
    MODE="pull"
    ENV_FILE="${2:-.env.route}"
    ;;
  "")
    ;;
  *)
    ENV_FILE="$1"
    ;;
esac
NAMESPACE="888router"
CONFIGMAP="888router-config"
SECRET="888router-secrets"
KUBE_CONTEXT="${KUBE_CONTEXT:-orbstack}"

if [ "$MODE" = "push" ] && [[ ! -f "$ENV_FILE" ]]; then
  echo "Error: $ENV_FILE not found."
  exit 1
fi

if [ "$(kubectl config current-context)" != "$KUBE_CONTEXT" ]; then
  echo "Error: refusing to sync secrets — current Kubernetes context is not $KUBE_CONTEXT."
  exit 1
fi

# ---- pull: K8s secret + configmap -> local dotenv file ------------------------
# Never echoes a secret value: the file is written with mode 600 and the summary
# prints key NAMES only.
if [ "$MODE" = "pull" ]; then
  command -v python3 >/dev/null || { echo "Error: python3 is required for --pull." >&2; exit 1; }
  kubectl --context "$KUBE_CONTEXT" -n "$NAMESPACE" get secret "$SECRET" >/dev/null
  kubectl --context "$KUBE_CONTEXT" -n "$NAMESPACE" get configmap "$CONFIGMAP" >/dev/null

  # The compose instance answers on a different origin than the k8s Ingress, and
  # it is served over plain HTTP on localhost — inheriting AUTH_COOKIE_SECURE=true
  # would make the browser refuse the session cookie.
  PUBLIC_URL="${PULL_URL_OVERRIDE:-http://localhost:20129}"
  COOKIE_SECURE="${PULL_COOKIE_SECURE:-false}"

  umask 077
  TMP_OUT="$(mktemp)"
  # The trap must cover the secret-bearing sidecars too, not just $TMP_OUT:
  # they hold the full base64 Secret/ConfigMap JSON, which is trivially
  # decodable, and a partial failure after the fetches would otherwise leave
  # them in $TMPDIR until reboot.
  trap 'rm -f "$TMP_OUT" "$TMP_OUT.secret" "$TMP_OUT.configmap"' EXIT INT TERM
  {
    printf '# Generated by scripts/k8s-sync-secret.sh --pull from %s/%s (context %s).\n' \
      "$NAMESPACE" "$SECRET" "$KUBE_CONTEXT"
    printf '# Secrets: DO NOT COMMIT (covered by the .env* rule in .gitignore).\n\n'
    # Both sources are read in one python pass so the secret values never touch
    # a shell variable, a process argument, or this script's stdout.
    kubectl --context "$KUBE_CONTEXT" -n "$NAMESPACE" get secret "$SECRET" -o json >"$TMP_OUT.secret"
    kubectl --context "$KUBE_CONTEXT" -n "$NAMESPACE" get configmap "$CONFIGMAP" -o json >"$TMP_OUT.configmap"
    PUBLIC_URL="$PUBLIC_URL" COOKIE_SECURE="$COOKIE_SECURE" \
      SECRET_JSON="$TMP_OUT.secret" CONFIGMAP_JSON="$TMP_OUT.configmap" python3 -c '
import os, json, base64
public_url = os.environ["PUBLIC_URL"]
over = {
    "BASE_URL": public_url,
    "NEXT_PUBLIC_BASE_URL": public_url,
    "NINEROUTER_PUBLIC_URL": public_url,
    "AUTH_COOKIE_SECURE": os.environ["COOKIE_SECURE"],
}
for key, value in sorted(json.load(open(os.environ["SECRET_JSON"]))["data"].items()):
    print(f"{key}={base64.b64decode(value).decode()}")
print()
print("# non-secret runtime config, copied from configmap/888router-config")
for key, value in sorted(json.load(open(os.environ["CONFIGMAP_JSON"]))["data"].items()):
    print(f"{key}={over.get(key, value)}")
'
  } >"$TMP_OUT"
  rm -f "$TMP_OUT.secret" "$TMP_OUT.configmap"

  grep -qE '^JWT_SECRET=.+' "$TMP_OUT" || { echo "Error: pulled file is missing JWT_SECRET — refusing to write $ENV_FILE." >&2; exit 1; }
  mv "$TMP_OUT" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo "✅ Pulled $NAMESPACE/$SECRET + $NAMESPACE/$CONFIGMAP -> $ENV_FILE (mode 600, $(grep -cE '^[A-Za-z_][A-Za-z0-9_]*=' "$ENV_FILE") keys, public origin $PUBLIC_URL)."
  echo "   Next: docker compose up -d 888route"
  exit 0
fi

# Strict dotenv parse: LAST occurrence wins, supports `export KEY=`, spaces
# around `=`, single/double quotes, and strips inline comments outside quotes.
dotenv_get() {
  local key="$1" line val
  line=$(grep -E "^[[:space:]]*(export[[:space:]]+)?${key}[[:space:]]*=" "$ENV_FILE" | tail -n 1 || true)
  if [ -z "$line" ]; then
    echo ""
    return
  fi
  val=${line#*=}
  val=$(printf '%s' "$val" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
  case "$val" in
    \"*\") val=${val#\"}; val=${val%\"} ;;
    \'*\') val=${val#\'}; val=${val%\'} ;;
    *) val=$(printf '%s' "$val" | sed -e 's/[[:space:]]*#.*$//') ;;
  esac
  printf '%s' "$val"
}

JWT_SECRET=$(dotenv_get JWT_SECRET)
API_KEY_SECRET=$(dotenv_get API_KEY_SECRET)
INITIAL_PASSWORD=$(dotenv_get INITIAL_PASSWORD)
MACHINE_ID_SALT=$(dotenv_get MACHINE_ID_SALT)
SEARXNG_SECRET=$(dotenv_get SEARXNG_SECRET)

invalid=0
for kv in "JWT_SECRET:$JWT_SECRET" "API_KEY_SECRET:$API_KEY_SECRET" "INITIAL_PASSWORD:$INITIAL_PASSWORD" "MACHINE_ID_SALT:$MACHINE_ID_SALT" "SEARXNG_SECRET:$SEARXNG_SECRET"; do
  key=${kv%%:*}
  val=${kv#*:}
  case "$val" in
    ""|*"change-me"*|*"placeholder"*|*"example"*|123456|password|secret)
      echo "Error: $key is missing, empty, or a placeholder — refusing to overwrite the existing Secret."
      invalid=1
      ;;
  esac
done
if [ "$invalid" -ne 0 ]; then
  exit 1
fi

kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply --context="$KUBE_CONTEXT" -f -

kubectl create secret generic 888router-secrets \
  --namespace="$NAMESPACE" \
  --from-literal=JWT_SECRET="${JWT_SECRET}" \
  --from-literal=API_KEY_SECRET="${API_KEY_SECRET}" \
  --from-literal=INITIAL_PASSWORD="${INITIAL_PASSWORD}" \
  --from-literal=MACHINE_ID_SALT="${MACHINE_ID_SALT}" \
  --from-literal=SEARXNG_SECRET="${SEARXNG_SECRET}" \
  --dry-run=client -o yaml | kubectl apply --context="$KUBE_CONTEXT" -f -

echo "✅ Secret 888router-secrets successfully synced to namespace $NAMESPACE."
