apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 888router

resources:
  - namespace.yaml
  - searxng-configmap.yaml
  - configmap.yaml
  - pvc.yaml
  - headroom.yaml
  - searxng.yaml
  - 888router.yaml
  - ingress.yaml
