apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 888router-data-pvc
  namespace: 888router
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
