apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
  namespace: 888router
data:
  settings.yml: |
    use_default_settings: true

    server:
      secret_key: "change-me-from-SEARXNG_SECRET"
      image_proxy: true
      limiter: false

    search:
      formats:
        - html
        - json
